//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 05:13:21 PM CET 
//


package classes.from.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dzieñ" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="31"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="miesi¹c" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;pattern value="I?X|XI{1,2}|I?V|V?I{1,3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rok" use="required" type="{http://www.w3.org/2001/XMLSchema}gYear" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "data", namespace = "http://czas.example.com")
public class Data {

    @XmlAttribute(name = "dzie\u0144", required = true)
    protected short dzieñ;
    @XmlAttribute(name = "miesi\u0105c", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String miesi¹c;
    @XmlAttribute(name = "rok", required = true)
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar rok;

    /**
     * Gets the value of the dzieñ property.
     * 
     */
    public short getDzieñ() {
        return dzieñ;
    }

    /**
     * Sets the value of the dzieñ property.
     * 
     */
    public void setDzieñ(short value) {
        this.dzieñ = value;
    }

    /**
     * Gets the value of the miesi¹c property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiesi¹c() {
        return miesi¹c;
    }

    /**
     * Sets the value of the miesi¹c property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiesi¹c(String value) {
        this.miesi¹c = value;
    }

    /**
     * Gets the value of the rok property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRok(XMLGregorianCalendar value) {
        this.rok = value;
    }

}
