//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 05:13:21 PM CET 
//


package classes.from.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://definicjeProwadzacych.example.com}definicjaProwadz¹cego" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "definicjaProwadzacego"
})
@XmlRootElement(name = "listaProwadz\u0105cych", namespace = "http://definicjeProwadzacych.example.com")
public class ListaProwadzacych {

    @XmlElement(name = "definicjaProwadz\u0105cego", namespace = "http://definicjeProwadzacych.example.com", required = true)
    protected List<DefinicjaProwadzacego> definicjaProwadzacego;

    /**
     * Gets the value of the definicjaProwadz¹cego property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the definicjaProwadz¹cego property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefinicjaProwadz¹cego().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DefinicjaProwadzacego }
     * 
     * 
     */
    public List<DefinicjaProwadzacego> getDefinicjaProwadzacego() {
        if (definicjaProwadzacego == null) {
            definicjaProwadzacego = new ArrayList<DefinicjaProwadzacego>();
        }
        return this.definicjaProwadzacego;
    }

}
