//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 05:13:21 PM CET 
//


package classes.from.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}autorzy"/>
 *         &lt;element ref="{}uczelnia"/>
 *         &lt;element ref="{}wydzia³"/>
 *         &lt;element ref="{}kierunek"/>
 *         &lt;element ref="{}semestr"/>
 *         &lt;element ref="{}specjalizacja"/>
 *         &lt;element ref="{http://czas.example.com}data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "autorzy",
    "uczelnia",
    "wydzia\u0142",
    "kierunek",
    "semestr",
    "specjalizacja",
    "data"
})
@XmlRootElement(name = "nag\u0142\u00f3wek")
public class Nag³ówek {

    @XmlElement(required = true)
    protected Autorzy autorzy;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String uczelnia;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String wydzia³;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String kierunek;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String semestr;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String specjalizacja;
    @XmlElement(namespace = "http://czas.example.com", required = true)
    protected Data data;

    /**
     * Gets the value of the autorzy property.
     * 
     * @return
     *     possible object is
     *     {@link Autorzy }
     *     
     */
    public Autorzy getAutorzy() {
        return autorzy;
    }

    /**
     * Sets the value of the autorzy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autorzy }
     *     
     */
    public void setAutorzy(Autorzy value) {
        this.autorzy = value;
    }

    /**
     * Gets the value of the uczelnia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUczelnia() {
        return uczelnia;
    }

    /**
     * Sets the value of the uczelnia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUczelnia(String value) {
        this.uczelnia = value;
    }

    /**
     * Gets the value of the wydzia³ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWydzia³() {
        return wydzia³;
    }

    /**
     * Sets the value of the wydzia³ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWydzia³(String value) {
        this.wydzia³ = value;
    }

    /**
     * Gets the value of the kierunek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKierunek() {
        return kierunek;
    }

    /**
     * Sets the value of the kierunek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKierunek(String value) {
        this.kierunek = value;
    }

    /**
     * Gets the value of the semestr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemestr() {
        return semestr;
    }

    /**
     * Sets the value of the semestr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemestr(String value) {
        this.semestr = value;
    }

    /**
     * Gets the value of the specjalizacja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecjalizacja() {
        return specjalizacja;
    }

    /**
     * Sets the value of the specjalizacja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecjalizacja(String value) {
        this.specjalizacja = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setData(Data value) {
        this.data = value;
    }

}
