//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 05:13:21 PM CET 
//


package classes.from.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}tytu³" minOccurs="0"/>
 *         &lt;element ref="{}imiê"/>
 *         &lt;element ref="{}nazwisko"/>
 *       &lt;/sequence>
 *       &lt;attribute name="kto" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tytu\u0142",
    "imi\u0119",
    "nazwisko"
})
@XmlRootElement(name = "prowadz\u0105cy")
public class Prowadz¹cy {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String tytu³;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String imiê;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String nazwisko;
    @XmlAttribute(name = "kto", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object kto;

    /**
     * Gets the value of the tytu³ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTytu³() {
        return tytu³;
    }

    /**
     * Sets the value of the tytu³ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTytu³(String value) {
        this.tytu³ = value;
    }

    /**
     * Gets the value of the imiê property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImiê() {
        return imiê;
    }

    /**
     * Sets the value of the imiê property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImiê(String value) {
        this.imiê = value;
    }

    /**
     * Gets the value of the nazwisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwisko() {
        return nazwisko;
    }

    /**
     * Sets the value of the nazwisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwisko(String value) {
        this.nazwisko = value;
    }

    /**
     * Gets the value of the kto property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getKto() {
        return kto;
    }

    /**
     * Sets the value of the kto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setKto(Object value) {
        this.kto = value;
    }

}
