//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 05:13:21 PM CET 
//


package classes.from.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}przedmiot" minOccurs="0"/>
 *         &lt;element ref="{}prowadz¹cy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://czas.example.com}czas" minOccurs="0"/>
 *         &lt;element ref="{}budynek" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="blok" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="6"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="rodzaj" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="wyk³ad"/>
 *             &lt;enumeration value="æwiczenia"/>
 *             &lt;enumeration value="laboratorium"/>
 *             &lt;enumeration value="okienko"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "przedmiot",
    "prowadz\u0105cy",
    "czas",
    "budynek"
})
@XmlRootElement(name = "zaj\u0119cia")
public class Zajêcia {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String przedmiot;
    protected List<Prowadz¹cy> prowadz¹cy;
    @XmlElement(namespace = "http://czas.example.com")
    protected Czas czas;
    protected Budynek budynek;
    @XmlAttribute(name = "blok", required = true)
    protected short blok;
    @XmlAttribute(name = "rodzaj", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rodzaj;

    /**
     * Gets the value of the przedmiot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrzedmiot() {
        return przedmiot;
    }

    /**
     * Sets the value of the przedmiot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrzedmiot(String value) {
        this.przedmiot = value;
    }

    /**
     * Gets the value of the prowadz¹cy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prowadz¹cy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProwadz¹cy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Prowadz¹cy }
     * 
     * 
     */
    public List<Prowadz¹cy> getProwadz¹cy() {
        if (prowadz¹cy == null) {
            prowadz¹cy = new ArrayList<Prowadz¹cy>();
        }
        return this.prowadz¹cy;
    }

    /**
     * Gets the value of the czas property.
     * 
     * @return
     *     possible object is
     *     {@link Czas }
     *     
     */
    public Czas getCzas() {
        return czas;
    }

    /**
     * Sets the value of the czas property.
     * 
     * @param value
     *     allowed object is
     *     {@link Czas }
     *     
     */
    public void setCzas(Czas value) {
        this.czas = value;
    }

    /**
     * Gets the value of the budynek property.
     * 
     * @return
     *     possible object is
     *     {@link Budynek }
     *     
     */
    public Budynek getBudynek() {
        return budynek;
    }

    /**
     * Sets the value of the budynek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Budynek }
     *     
     */
    public void setBudynek(Budynek value) {
        this.budynek = value;
    }

    /**
     * Gets the value of the blok property.
     * 
     */
    public short getBlok() {
        return blok;
    }

    /**
     * Sets the value of the blok property.
     * 
     */
    public void setBlok(short value) {
        this.blok = value;
    }

    /**
     * Gets the value of the rodzaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRodzaj() {
        return rodzaj;
    }

    /**
     * Sets the value of the rodzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRodzaj(String value) {
        this.rodzaj = value;
    }

}
