//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.30 at 05:13:21 PM CET 
//


package classes.from.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZbiórPlanówZajêæ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZbiórPlanówZajêæ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}nag³ówek"/>
 *         &lt;element ref="{http://definicjeProwadzacych.example.com}listaProwadz¹cych"/>
 *         &lt;element ref="{}plan"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zbi\u00f3rPlan\u00f3wZaj\u0119\u0107", propOrder = {
    "nag\u0142\u00f3wek",
    "listaProwadz\u0105cych",
    "plan"
})
@XmlRootElement(name = "plany")
public class ZbiórPlanówZajêæ {

    @XmlElement(required = true)
    protected Nag³ówek nag³ówek;
    @XmlElement(namespace = "http://definicjeProwadzacych.example.com", required = true)
    protected ListaProwadz¹cych listaProwadz¹cych;
    @XmlElement(required = true)
    protected Plan plan;

    /**
     * Gets the value of the nag³ówek property.
     * 
     * @return
     *     possible object is
     *     {@link Nag³ówek }
     *     
     */
    public Nag³ówek getNag³ówek() {
        return nag³ówek;
    }

    /**
     * Sets the value of the nag³ówek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nag³ówek }
     *     
     */
    public void setNag³ówek(Nag³ówek value) {
        this.nag³ówek = value;
    }

    /**
     * Gets the value of the listaProwadz¹cych property.
     * 
     * @return
     *     possible object is
     *     {@link ListaProwadz¹cych }
     *     
     */
    public ListaProwadz¹cych getListaProwadz¹cych() {
        return listaProwadz¹cych;
    }

    /**
     * Sets the value of the listaProwadz¹cych property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaProwadz¹cych }
     *     
     */
    public void setListaProwadz¹cych(ListaProwadz¹cych value) {
        this.listaProwadz¹cych = value;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return
     *     possible object is
     *     {@link Plan }
     *     
     */
    public Plan getPlan() {
        return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plan }
     *     
     */
    public void setPlan(Plan value) {
        this.plan = value;
    }

}
